/**
 * @fileOverview KpiViewTable
 * @change
    #1A by prcjack @2012/7/27 Creates file.
	#2M by prcjack @2012/8/17 Modify to support cell width.
	#3A by prcjack @2012/9/7 Add empty msg support for no rows data to display.
	#4M by prcjack @2012/9/7 Add check list type b4 calling Array.map to make sure the result type is array.
	#5M by prcjack @2013/4/6 Modify add "div" to wrap table because ie table element cant use innerHTML feature.
	#6M by prcjack @2013/8/18 Modify css scope to "rl_databox_data_list", add "data_ctn" css for table cell.
 */
orderjs.define("app.dataBox.KpiViewTable",["app.dataBox.engine","css>rl:databox"],function(){rl.dataBox.KpiViewTable=rl.createClass({parent:rl.dataBox.KpiViewHtml,construct:function(t){rl.isPrototyping(arguments[0])||rl.dataBox.KpiViewTable.parent.call(this,t)},members:{columns:null,data:null,dynamicColumns:!0,emptyMsg:rl.getG11nSource("emptyMsg")||"No data",_htmlTpl:new rl.HtmlTpl('<div id="{id}">{tableHtml}</div>'),_tableTpl:new rl.HtmlTpl('<table class="rl_databox_data_list" border="0" cellspacing="0" cellpadding="0">{headerHtml}{rowsHtml}</table>'),_thTpl:new rl.HtmlTpl('<th class="label" style="{widthStyle}"><div style="{widthStyle}">{caption}</div></th>'),_tdTpl:new rl.HtmlTpl('<td class="data_ctn" {colspanAttr}><div style="word-break:break-all; {widthStyle}">{value}</div></td>'),getEmptyRowHtml:function(){var t,l=this._tdTpl;return t=l.assign({value:this.emptyMsg,colspanAttr:'colspan="'+this.columns.length+'"'}),t="<tr>"+t+"</tr>"},getHeaderHtml:function(){var t,l,e=this._thTpl,a=this.columns;return a&&a.length>0?(t=Array.map(function(t){return l=rl.fill({widthStyle:rl.isDefined(t.width)?"width : "+rl.dom.addUnit(t.width)+";":""},t),e.assign(l)},a),t="<tr>"+t.join("")+"</tr>"):t="",t},getRowHtml:function(t){var l,e=this._tdTpl;return l=Array.map(function(l){var a=t[l.name];return rl.isFunction(l.convert)&&(a=l.convert(a)),e.assign({value:a,widthStyle:rl.isDefined(l.width)?"width : "+rl.dom.addUnit(l.width)+";":""})},this.columns),l="<tr>"+l.join("")+"</tr>"},getRowsHtml:function(){var t,l=this.data,e=this.columns;return e&&e.length>0&&l&&l.length>0?(t=Array.map(this.getRowHtml,l,this),t=t.join("")):t=this.getEmptyRowHtml(),t},getRenderHtml:function(){return this._htmlTpl.assign({id:this.id,tableHtml:this.getTableHtml()})},getTableHtml:function(){return this._tableTpl.assign({headerHtml:this.getHeaderHtml(),rowsHtml:this.getRowsHtml()})},loadData:function(t){if(!rl.isObject(t)){var l=this+"-> loadData(): Invalid data = "+t;throw{description:l}}this.dynamicColumns?(rl.isArray(t.columns)&&(this.columns=t.columns),this.data=t.data):this.data=t,this._rendered?this.dw.setInnerHTML(this.getTableHtml()):this.render()},toString:function(){return"[object rl.dataBox.KpiViewTable]"}}})});