/**
 * @fileOverview JqueryAjaxDirect class.
 * @change
 	#1 by prcjack Creates file.
	#2 by prcjack @2014/10/29 
		Add cancel default for succ and error handlers.
		Add ignoreAbortError option.
		Handlers can define msg by its return string.
 */
orderjs.define("lib.rpc.JqueryAjaxDirect",["open.jquery.jquery"],function(){var r=this.track,e=orderjs("open.jquery.jquery"),s=rl.createClass({parent:rl.util.EventProvider,construct:function(){rl.isPrototyping(arguments[0])||(s.parent.apply(this,arguments),this.initialize.apply(this,arguments))},members:{enableSDT:!0,ignoreAbortError:!0,msgs:null,services:null,showErrMsg:function(r){alert(r)},showSuccMsg:!1,initialize:function(r){e.extend(!0,this,{msgs:s.defaultMsgs},r),rl.isObject(this.services)||(this.services={})},getMsg:function(r,e){var s,t=this.msgs;return rl.isNonNullStr(e)&&(s=t[e+"."+r]),s||t[r]},invoke:function(e,s){var t,i,n=this.services[e];if(!rl.isFunction(n)){var o="Service = "+e+" is not provided in direct!",a={service:e,direct:this};return rl.raiseError(o,r(this,"invoke",a))}return t=rl.ext({processName:e},s),this._wrapDirectSuccess(t),this._wrapDirectError(t),i=[t].concat(rl.slice(arguments,2)),n.apply(this,i)},notifyError:function(r,e,s,t){var i,n=t||{};if(i=s||this.getMsg(e,r),rl.config.debugMode){var o=n.url;rl.isNonNullStr(o)&&(o=rl.format('<a href="{0}" target="_blank">{0}</a>',[o])),rl.dir({process:r,type:e,url:o,msg:i},this+" notifyError(): Direct call failed! ",{type:"err"})}rl.isFunction(this.showErrMsg)&&rl.isNonNullStr(i)&&(n.showErrMsg||this.showErrMsg)(i)},notifySuccess:function(r,e){var s=this.getMsg("success",r),t=e||{};if(rl.config.debugMode){var i=t.url;rl.isNonNullStr(i)&&(i=rl.format('<a href="{0}" target="_blank">{0}</a>',[i])),rl.dir({process:r,url:i,msg:s},this+" notifySuccess(): Direct call success! ")}rl.isFunction(this.showSuccMsg)&&rl.isNonNullStr(s)&&(t.showSuccMsg||this.showSuccMsg)(s)},_wrapDirectError:function(r){var e=this,s=r.error,t=r.processName;r.error=function(i,n,o){if(0!=i.readyState||!e.ignoreAbortError){var a;if(rl.isFunction(s))try{if(a=s.apply(null,arguments),a===!1)return}catch(o){rl.debug(e+" _wrapDirectError(): onerror err = "+o,"err"),a=e.getMsg("handler.error",t)}var c="ajax"+(n?"."+n:".error");e.notifyError(t,c,a,r)}}},_wrapDirectSuccess:function(r){var e=this,s=r.success,t=r.sdtError,i=r.processName;r.success=function(n,o,a){var c;try{e.enableSDT?1==n.status?rl.isFunction(s)&&(c=s(n.data,n,o,a)):c=rl.isFunction(t)?t(n.data,n,o,a):n.msg||e.getMsg("ajax.dataerror",i):rl.isFunction(s)&&(c=s.apply(null,arguments))}catch(l){rl.debug(e+" _wrapDirectSuccess(): onsuccess err = "+l,"err"),c=e.getMsg("handler.error",i)}c!==!1&&(rl.isDefined(c)?e.notifyError(i,"ajax.dataerror",c,r):e.notifySuccess(i,r))}},toString:function(){return"[object JqueryAjaxDirect]"}}});return s.defaultMsgs={"handler.error":"页面脚本发生错误！","ajax.error":"请求失败！","ajax.timeout":"请求超时！","ajax.parsererror":"数据解析错误！","ajax.notmodified":"数据未修改！","ajax.dataerror":"数据读取错误！"},s});