/**
 * @fileOverview Defines zTree list page.
 * Note: this module required shim:
 * <code>
	orderjs.config("shim", {
		"open.zTree.jquery-ztree-core" : {
			deps : ["open.jquery.jquery"]
		}
	});
 * </code>
 * @change
 	#1 by prcjack @2014/09/25 Creates file.
 */
orderjs.define("x:mti.zTreeListPage",["open.jquery.jquery","open.zTree.jquery-ztree-core","css>open.zTree.css.zTreeStyle","lib.util.StateObserver","lib.util.OneshotEventProvider","gui.box.Div","gui.box.Box"],function(){var e=orderjs("open.jquery.jquery");rl.createNamespace("rlx.mti",{listRenderDog:new rl.util.StateObserver("moduleReady, mainLayoutReady"),processEventMgr:new rl.util.OneshotEventProvider,createTree:function(r){var t=rlx.mti.listPageTreeNodes,i=e.extend(!0,{data:{simpleData:{pIdKey:"pid",enable:!0}},callback:{onClick:function(e,r,t){i.loadGridByNode(t.id)}}},r);return t&&t.length>0||rl.debug(this+" createTree() rlx.mti.listPageTreeNodes is unready = "+t,"err"),e.fn.zTree.init(e(i.treeId),i,t)},createSideBox:function(r){return new rl.gui.box.Div(e.extend(!0,{iniStyle:{borderRight:"solid 1px #a6c2e6",backgroundColor:"#fff"},isHtmlContent:!0},r))},createTreeListPage:function(e){var r=rlx.mti;r._treeListPageCreated||(r._treeListPageCreated=!0,r.processEventMgr.on("treeNodesReady",function(){rl.onReady(function(){r.initMainLayout(e),orderjs("x:mti.listPage"),orderjs(function(){r.listRenderDog.update("moduleReady")})})}),r.listRenderDog.on("ready",function(){r.initListBox(e),r.loadTreeFirstNode(),r.cancelListPageGridSearchFormSubmit()}))},initMainLayout:function(e){var r=rlx.mti;rl.body.on("render",function(){r.listPageTree=rlx.mti.createTree(e.tree),r.listRenderDog.update("mainLayoutReady"),r.processEventMgr.fireEvent("mainLayoutReady")}),r.listPageSideBox=rlx.mti.createSideBox(e.sideBox),rl.layoutBody({west:{iniSize:200,comp:r.listPageSideBox},center:{}})},initListBox:function(e){var r=rlx.mti;e.searchDialog&&(orderjs("gui.dialog.Dialog"),orderjs(function(){var t=rl.ext({},e.searchDialog);r.listPageSearchDialog=r.createSearchDialog(t),t.autoSearchOnPressEnter!==!1&&r.addAutoSearchToSearchDialog()})),e.toolbar&&(r.listPageToolbar=r.createToolbar(e.toolbar)),r.listPageGrid=r.createGrid(rl.ext(e.grid,{autoRenderOnReady:!1,loadDataBeforeRender:!1})),r.listBox=new rl.gui.box.Box({layoutType:rl.gui.layout.BorderLayout,id:"listBox",autoRenderOnReady:!1,layoutConfig:{north:e.toolbar?{iniSize:30,comp:r.listPageToolbar}:null,center:{margin:"0 2 0 5",comp:r.listPageGrid}}}),rl.body.layout.addLayoutComponent(r.listBox,"center"),r.processEventMgr.fireEvent("listBoxReady")},loadTreeFirstNode:function(){var e=rlx.mti,r=e.listPageTreeNodes;r&&r[0]&&(e.listPageTree.selectNode(e.listPageTree.getNodes()[0]),e.listPageTree.setting.loadGridByNode(r[0].id))}})});